/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HomeReferenceRouteImport } from './routes/home-reference'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as LocaleFranceCityRouteImport } from './routes/$locale/france/$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeReferenceRoute = HomeReferenceRouteImport.update({
  id: '/home-reference',
  path: '/home-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFranceCityRoute = LocaleFranceCityRouteImport.update({
  id: '/$locale/france/$city',
  path: '/$locale/france/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home-reference': typeof HomeReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/france/$city': typeof LocaleFranceCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-reference': typeof HomeReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/france/$city': typeof LocaleFranceCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home-reference': typeof HomeReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/france/$city': typeof LocaleFranceCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home-reference'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale/'
    | '/$locale/france/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home-reference'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale'
    | '/$locale/france/$city'
  id:
    | '__root__'
    | '/'
    | '/home-reference'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale/'
    | '/$locale/france/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeReferenceRoute: typeof HomeReferenceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleFranceCityRoute: typeof LocaleFranceCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-reference': {
      id: '/home-reference'
      path: '/home-reference'
      fullPath: '/home-reference'
      preLoaderRoute: typeof HomeReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/france/$city': {
      id: '/$locale/france/$city'
      path: '/$locale/france/$city'
      fullPath: '/$locale/france/$city'
      preLoaderRoute: typeof LocaleFranceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeReferenceRoute: HomeReferenceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleFranceCityRoute: LocaleFranceCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
